name:                agda-language-server
version:             0.2.1
github:              "banacorn/agda-language-server"
license:             MIT
author:              "Ting-Gian LUA"
maintainer:          "banacorn@gmail.com"
copyright:           "2020 Author name here :)"

extra-source-files:
- README.md
- CHANGELOG.md
- stack.yaml
- package.yaml

# Metadata used when publishing your package
synopsis:            An implementation of language server protocal (LSP) for Agda 2. 
category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/banacorn/agda-language-server#readme>

dependencies:
  - base >= 4.7 && < 5
  - Agda == 2.6.2.2
  - aeson
  - bytestring
  - containers
  - lsp < 2
  - mtl
  - network
  - network-simple
  - strict
  - stm
  - text
  - process

library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-patterns
  - -Wunused-do-bind
  - -Wunused-foralls
  - -Wwarnings-deprecations
  - -Wwrong-do-bind
  - -Wmissing-fields
  - -Wmissing-methods
  - -Wmissing-pattern-synonym-signatures
  - -Wmissing-signatures
  - -Werror=incomplete-patterns
  - -fno-warn-orphans
  default-extensions:
  - LambdaCase
  - OverloadedStrings

executables:
  als:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wincomplete-patterns
    - -Wunused-do-bind
    - -Wunused-foralls
    - -Wwarnings-deprecations
    - -Wwrong-do-bind
    - -Wmissing-fields
    - -Wmissing-methods
    - -Wmissing-pattern-synonym-signatures
    - -Wmissing-signatures
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror=incomplete-patterns
    - -fno-warn-orphans
    dependencies:
    - agda-language-server

tests:
  als-test:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-golden
      - tasty-quickcheck

    ghc-options:
      - -Wincomplete-patterns
      - -Wunused-do-bind
      - -Wunused-foralls
      - -Wwarnings-deprecations
      - -Wwrong-do-bind
      - -Wmissing-fields
      - -Wmissing-methods
      - -Wmissing-pattern-synonym-signatures
      - -Wmissing-signatures
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror=incomplete-patterns
      - -fno-warn-orphans

    default-extensions:
      - LambdaCase
      - OverloadedStrings

# tests:
#   als-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - agda-language-server
